import React from 'react';

export default function FooterSection({ page }) {
  return (
    <div className="flex justify-between text-sm text-gray-500 px-4 py-2 border-t mt-4">
      <span>Generated by ArmeniaBankApp</span>
      <span>Page {page}</span>
    </div>
  );
}
